// This file is generated by Slice Machine. Update with care!

import Features from './Features';
import MySlice from './MySlice';
import TextImageRight from './TextImageRight';

export {
	Features,
	MySlice,
	TextImageRight,
};

export const components = {
	features: Features,
	my_slice: MySlice,
	text_image_right: TextImageRight,
};
